#!/bin/bash
readonly SCALE=1.66666x1.66666

mapfile -t outputs < <(xrandr -q | grep '\<connected' | awk -F ' ' '{print $1}' | grep -v eDP-1)
num_outputs=${1:-${#outputs[*]}}

if [[ "$1" == "curve" ]]
then
  xrandr --output "${outputs[0]}" --auto --output eDP-1 --auto
  xrandr --output "${outputs[0]}" --scale 1.4x1.4 --panning 4816x2016 --output eDP-1 --off
  exit 0
fi

if [[ "$num_outputs" == 2 ]]
then
  echo "Setting two monitors"
  xrandr --output "${outputs[0]}" --auto --output "${outputs[1]}" --auto
  xrandr --output "${outputs[0]}" --scale $SCALE --pos 0x0 --output "${outputs[1]}" --scale $SCALE --pos 3200x0 --fb 6400x1800 --output eDP-1 --off
elif [ "$num_outputs" == 1 ]
then
  xrandr --output "${outputs[0]}" --auto --output eDP-1 --auto
  xrandr --output "${outputs[0]}" --scale $SCALE --same-as eDP-1 --output eDP-1 --auto --panning 3200x1800
elif [ "$num_outputs" == 0 ]
then
  echo "Setting default monitor"
  xrandr --output eDP-1 --auto
  xrandr --output "${outputs[0]}" --off --output "${outputs[1]}" --off --fb 2880x1800 --output eDP-1 --auto
else
  echo "Unknown argument"
fi

feh --bg-scale ~/images/wallpaper.jpg
